x=[1,2,3,4,5,6,7,8];
N=length(x);
X=fft(x);
x_reversed=fliplr(x);
X_reversed=fft(x_reversed);
figure;
subplot(2,2,1);
stem(0:N-1,x,"filled");
xlabel('n');
ylabel('x[n]');
subplot(2, 2, 2);
stem(0:N-1, abs(X), 'filled');
title('DFT of Original Signal (Magnitude)');
xlabel('k');
ylabel('|X[k]|');
subplot(2, 2, 3);
stem(0:N-1, x_reversed, 'filled');
title('Time-Reversed Signal (Time Domain)');
xlabel('n');
ylabel('x[N-n]');
subplot(2, 2, 4);
stem(0:N-1, abs(X_reversed), 'filled');
title('DFT of Time-Reversed Signal (Magnitude)');
xlabel('k');
ylabel('|X[N-k]|');